name: Build & Test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.ref_name || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  BUILD_CACHE_KEY: ${{ github.sha }}
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/packages/*/dist

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Setup NPM dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Store dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: dist/**

  test:
    name: Smoke Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Setup NPM dependencies
        run: npm install

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
          merge-multiple: true

      - name: Smoke test
        run: |
            node dist/cli.js

      - name: Test with asset
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
            cd test
            node ../dist/cli.js -a asset.txt --no-bundle sample.cjs
            expected=$(cat asset.txt)
            actual=$(./dist-bin/sample-linux-x64)
            [ "$actual" = "yolo" ]
